### ISSUE TITLE
exclude doesn't support multiple params.

### ISSUE THREAD

**Issue by datacurse** [jimfilippou/repo2txt#6]
Doesn't work:
```
PS> npx repo2txt . --exclude "public" ".dependency-cruiser.cjs"
Too many arguments, expected 1 but encountered ".dependency-cruiser.cjs"
```

Does work:
```
PS> npx repo2txt . --exclude "public" --exclude ".dependency-cruiser.cjs"
Repository contents have been written to repo2txt.txt
```

**Comment by jimfilippou** [comment]
Thanks for the feature request, checking..

**Comment by jimfilippou** [comment]
Was fixed in this release https://github.com/jimfilippou/repo2txt/releases/tag/v0.2.1 you can use it like this

```
npx repo2txt@latest . --exclude public,.dependency-cruiser.cjs
```

Happy holidays, thanks for the request 🎅🏼

**Comment by datacurse** [comment]
> Was fixed in this release https://github.com/jimfilippou/repo2txt/releases/tag/v0.2.1 you can use it like this
> 
> ```
> npx repo2txt@latest . --exclude public,.dependency-cruiser.cjs
> ```
> 
> Happy holidays, thanks for the request 🎅🏼

yo! thanks for the fix!

ive checked it out, im using the recent version which is 0.2.1 and im facing the issue that if i list more than one file/path to ignore separated by , it ignores all of them. Works if i specify only one file/path. Do you have any ideas what could cause it?
